### ISSUE TITLE
Unable to decompose arrays more than 1 level deep

### ISSUE THREAD

**Issue by Michael-Stock** [i-e-b/node-tree-surgeon#11]
When decomposing arrays more than one level deep, the result from rendering reduces the array level to 1 level deep:

{
  "TargetDate": "2014-09-22",
  "TargetTypes": [
    "Package"
  ],
  "Classifications": [
    [
      "31717084-939f-4a5f-82f0-b33863bf62ea"
    ]
  ],
  "Select": [
    "Name",
    "ChildEntity.Name"
  ]
}

For classifications, when rendering we get:

  "Classifications": [
      "31717084-939f-4a5f-82f0-b33863bf62ea"
  ],

Instead of:

  "Classifications": [
    [
      "31717084-939f-4a5f-82f0-b33863bf62ea"
    ]
  ],

**Comment by i-e-b** [comment]
this doesn't make great sense in a non manifold relation. Agreed to treat bare nested arrays as simple values.
