### ISSUE TITLE
Decompose to include object types

### ISSUE THREAD

**Issue by AGascoigne** [i-e-b/node-tree-surgeon#5]
## Decompose with node (object) types  ##
*tree-surgeon* labels each relations with a "Kind", this is how the parent refers to the child in the relation. "Kind" is essential as it provides the method for composing the POJO again from the relational model. For example, decomposing the following:

    var person = {
	    Name: "Someone",
	    Landline: {
		    CountryCode: "44",
		    Number: "1234567890"
		},
	    Mobile: {
		    CountryCode: "44",
		    Number: "7776667777"
		},
	}
marks the Relation between *person* and the *Telephone Numbers* with the Kinds of "Landline" and "Mobile". 

This becomes problematic if the user wishes to work with all phone numbers; with the current version this would require either inspecting all nodes to decide they are a phone number of making multiple "xxxxByKind" calls as long as the Kinds were known.

The proposal is to decorate Relations in the relational model which *tree-surgeon* builds with an additional (string) property indicating the ObjectType of the Child (name suggestions: ChildType, ObjectType, Node Type etc.). 

### Changes ###

 1. **decompose** The determination of the ObjectType will be done via a function passed to the Decompose method. The function will be similar to the function to pick Ids, it will accept a single parameter of the child object and it will return the name of the ObjectType.
 2. **xxxxByType methods** Provide methods similar to the "xxxByKind" methods to work on sets of the same type, for example `chopByType(type, predicate, relationalModel)` -- *given the name of an ObjectType it will call the provided data predicate for each child which matches the type.*

**Comment by i-e-b** [comment]
This could probably be done quite lightly by further abstracting some of the `pickIdsBy...` functions.

**Comment by i-e-b** [comment]
Decompose with types in now supported with `decompose(input, relationDecorator)`
